<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="60381" started-at="2019-06-21T07:26:26Z" finished-at="2019-06-21T07:27:26Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="60381" started-at="2019-06-21T07:26:26Z" finished-at="2019-06-21T07:27:26Z">
      <class name="com.training.sanity.tests.DatabaseTest_AddCategory_RTTC066">
        <test-method status="PASS" signature="setUpBeforeClass()[pri:0, instance:com.training.sanity.tests.DatabaseTest_AddCategory_RTTC066@3e6fa38a]" name="setUpBeforeClass" is-config="true" duration-ms="24" started-at="2019-06-21T07:26:26Z" finished-at="2019-06-21T07:26:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.sanity.tests.DatabaseTest_AddCategory_RTTC066@3e6fa38a]" name="setUp" is-config="true" duration-ms="37872" started-at="2019-06-21T07:26:27Z" finished-at="2019-06-21T07:27:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="DatabaseTest_AddCategory_RTTC066(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.training.sanity.tests.DatabaseTest_AddCategory_RTTC066@3e6fa38a]" name="DatabaseTest_AddCategory_RTTC066" duration-ms="20882" started-at="2019-06-21T07:27:04Z" data-provider="db-inputs" finished-at="2019-06-21T07:27:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[ORNAMENTS]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[ornaments for ladies]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[ORNAMENTS]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[ornaments for ladies]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ornaments for ladies] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ornaments for ladies] but found [null]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.training.sanity.tests.DatabaseTest_AddCategory_RTTC066.DatabaseTest_AddCategory_RTTC066(DatabaseTest_AddCategory_RTTC066.java:88)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DatabaseTest_AddCategory_RTTC066 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.training.sanity.tests.DatabaseTest_AddCategory_RTTC066@3e6fa38a]" name="tearDown" is-config="true" duration-ms="920" started-at="2019-06-21T07:27:25Z" finished-at="2019-06-21T07:27:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.training.sanity.tests.DatabaseTest_AddCategory_RTTC066 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
